ALTER TABLE generation_requests
    ADD COLUMN IF NOT EXISTS prompt_version TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS skill_id TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS skill_version TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS retrieved_knowledge_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS raw_output JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS parsed_output JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS input_tokens INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS output_tokens INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_tokens INT NOT NULL DEFAULT 0;

